SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.18


PLAYER_LIVES = 3
RESPAWN_SECONDS = 2.0
SHOT_LIFETIME_SECONDS = 1.6
BACKGROUND = "#101327"
FOREGROUND = "#eef3e8"
ACCENT = "#83efd0"
DANGER = "#f18c83"
MUTED = "#a4adc5"
